version: "3.7"

services:
  frontend:
    image: instapound_frontend
    container_name: instapound-frontend
    build:
      context: ./frontend

  backend:
    image: instapound_backend
    container_name: instapound-backend
    restart: always
    build:
      context: ./backend
    depends_on:
      - mongo

  nginx:
    image: instapound_nginx
    container_name: instapound-nginx
    build:
      context: ./nginx
    ports:
      - 4200:80
    restart: unless-stopped
    depends_on:
      - frontend

  mongo:
    image: mongo
    container_name: instapound-mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./database:/data/db
