version: "3.7"

services:
  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: instapound-database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${DB_PORT}
    volumes:
      - ./database:/var/lib/data

  frontend:
    image: instapound_frontend
    container_name: instapound-frontend
    build:
      context: ./frontend

  backend:
    image: instapound_backend
    container_name: instapound-backend
    restart: unless-stopped
    build:
      context: ./backend
    env_file:
      - ./.env
    depends_on:
      - database

  nginx:
    image: instapound_nginx
    container_name: instapound-nginx
    build:
      context: ./nginx
    ports:
      - 4200:80
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
