version: "3.7"

services:
  frontend:
    build:
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend:/frontend:delegated
      - /frontend/node_modules

  backend:
    build:
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend:/backend:delegated
      - /backend/node_modules
