version: "3.7"

services:
  frontend:
    image: instapound_frontend
    container_name: instapound-frontend
    build:
      context: ./frontend

  backend:
    image: instapound_backend
    container_name: instapound-backend
    restart: unless-stopped
    build:
      context: ./backend
    env_file:
      - ./.env

  nginx:
    image: instapound_nginx
    container_name: instapound-nginx
    build:
      context: ./nginx
    ports:
      - 4200:80
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
